# Generated by Django 4.2.3 on 2023-07-27 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_apikey_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default=uuid.UUID, max_length=255),
        ),
    ]
