# Generated by Django 4.2.3 on 2023-07-27 16:44

import apikey.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_apikey_id_alter_apikey_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.UUIDField(default=apikey.authentication.models.ApiKeyManager.generate_api_key, editable=False, primary_key=True, serialize=False),
        ),
    ]
