# Generated by Django 4.2.3 on 2023-07-27 16:45

import apikey.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_apikey_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default=apikey.authentication.models.ApiKeyManager.generate_api_key, editable=False, max_length=255),
        ),
    ]
