# Generated by Django 4.2.3 on 2023-07-27 17:18

import apikey.authentication.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('authentication', '0007_alter_apikey_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expiration_time',
            field=models.DateTimeField(default='2023-07-27 12:14:02.562696', verbose_name=datetime.datetime(2023, 7, 28, 17, 18, 36, 15451, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default=apikey.authentication.models.ApiKeyManager.generate_api_key, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='company.company'),
        ),
    ]
