# Generated by Django 4.2.3 on 2023-07-27 17:20

import apikey.authentication.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_apikey_expiration_time_apikey_is_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default=apikey.authentication.models.ApiKeyManager.generate_api_key, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='expiration_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 7, 28, 17, 20, 13, 45502, tzinfo=datetime.timezone.utc)),
        ),
    ]
