# Generated by Django 4.2.3 on 2023-07-27 17:32

import apikey.authentication.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_apikey_api_key_alter_apikey_expiration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='is_valid',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default=apikey.authentication.models.ApiKeyManager.generate_api_key, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 17, 32, 14, 450993, tzinfo=datetime.timezone.utc)),
        ),
    ]
