# Generated by Django 4.2.3 on 2023-07-27 17:39

import apikey.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_apikey_is_valid_alter_apikey_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='expiration_time',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default=apikey.authentication.models.ApiKeyManager.generate_api_key, editable=False, max_length=255),
        ),
    ]
